"""!@test_output_conversion.py
@brief This module contains a pytest function for the solve_sudoku_wrapper function
@details The test function contained by this module tests that the solve_sudoku_wrapper function of the src module can
solve an example sudoku puzzle successfully.
@author Created by C. Factor on 07/12/2023
"""
from src.solve_sudoku import solve_sudoku_wrapper
import numpy as np


def test_solve_sudoku_wrapper():
    """
    @brief Test that the solve_sudoku_wrapper function can solve an example puzzle.
    @details The test function checks that the solve_sudoku_wrapper function can solve an example puzzle. The example
    puzzle was generated by asking ChatGPT to give me an example puzzle with prompt:
    "example sudoku puzzle and answer in python as numpy array"
    @return True if the test is successful, otherwise False.
    """
    puzzle = np.array(
        [
            [5, 3, 0, 0, 7, 0, 0, 0, 0],
            [6, 0, 0, 1, 9, 5, 0, 0, 0],
            [0, 9, 8, 0, 0, 0, 0, 6, 0],
            [8, 0, 0, 0, 6, 0, 0, 0, 3],
            [4, 0, 0, 8, 0, 3, 0, 0, 1],
            [7, 0, 0, 0, 2, 0, 0, 0, 6],
            [0, 6, 0, 0, 0, 0, 2, 8, 0],
            [0, 0, 0, 4, 1, 9, 0, 0, 5],
            [0, 0, 0, 0, 8, 0, 0, 7, 9],
        ]
    )

    puzzle_answer = np.array(
        [
            [5, 3, 4, 6, 7, 8, 9, 1, 2],
            [6, 7, 2, 1, 9, 5, 3, 4, 8],
            [1, 9, 8, 3, 4, 2, 5, 6, 7],
            [8, 5, 9, 7, 6, 1, 4, 2, 3],
            [4, 2, 6, 8, 5, 3, 7, 9, 1],
            [7, 1, 3, 9, 2, 4, 8, 5, 6],
            [9, 6, 1, 5, 3, 7, 2, 8, 4],
            [2, 8, 7, 4, 1, 9, 6, 3, 5],
            [3, 4, 5, 2, 8, 6, 1, 7, 9],
        ]
    )
    assert (solve_sudoku_wrapper(puzzle) == puzzle_answer).all()
